#!/usr/bin/env python
"""cli.py - auto-generated by softnanotools"""
from argparse import ArgumentParser
from softnanotools.js.core import JSONReader
from softnanotools.logger import Logger
logger = Logger(__name__)

def run(
    command: str,
    kind: str,
    **kwargs
):
    assert command == 'js'
    if kind == 'replace':
        JSONReader.replace(**kwargs)
    return

def main():
    parser = ArgumentParser()
    parser.add_argument('kind')
    parser.add_argument('fname')
    parser.add_argument('key')
    parser.add_argument('value')
    run(**vars(parser.parse_args()))
    return

if __name__ == '__main__':
    import doctest
    doctest.testmod()
