#!/usr/bin/env python
"""core.py - auto-generated by softnanotools"""
import json
from pathlib import Path
from typing import Any
from softnanotools.logger import Logger
logger = Logger(__name__)

class JSONReader:
    """A JSONReader stores file information about a JSON file"""
    def __init__(self, fname: Path):
        self.fname = fname
        self.data = {}
        self.raw = ""
        self.read()

    def read(self):
        """Sets JSONReader.data and JSONReader.raw by opening and
        reading JSONReader.fname"""
        with open(self.fname, 'r') as f:
            string = f.read()
            self.raw = string
            self.data = json.loads(string)
        return

    def write(self, output: Path):
        """Writes a """
        with open(output, 'w') as f:
            json.dump(f, indent=2)
        return

    @staticmethod
    def replace(fname: Path, key: str, value: Any):
        reader = JSONReader(fname)
        reader.data[key] = value
        reader.write(fname)
        return



if __name__ == '__main__':
    import doctest
    doctest.testmod()
